// playlist_ram.sv - loads playlist.bin (slot 17) at boot; exposes per-track
// start_chunk, chunk_count, title (64 chars), artist (32 chars), and
// audio_bank (which "Audio Bank N" data slot this track's audio lives in).
//
// playlist.bin layout (128 bytes per track, big-endian APF delivery):
//   Word  0 (bytes   0-  3)  [31:16]=start_chunk  [15:0]=chunk_count
//   Words 1-16 (bytes  4- 67)  track title: 64 ASCII chars, 4 per word, [31:24]=char0
//   Words17-24 (bytes 68- 99)  artist name: 32 ASCII chars, 4 per word, [31:24]=char0
//   Word 25 (byte 100)      [31:24]=audio_bank (0..15, only low 4 bits used)
//   Word 25 (bytes101-103) + Words26-31 (bytes104-127)  reserved/zero
//
// Section 41 follow-up: start_chunk's on-disk MEANING changed from a global
// offset into one giant audio file to a LOCAL offset within whichever
// "Audio Bank N" data slot audio_bank names - see POCKETPLAYER_NOTES.txt for
// why (a 32-bit target_dataslot_slotoffset field hard-caps any single data
// slot at 4GB/8192 chunks; splitting into multiple bank files/slots was the
// fix). This file's bit position/width for start_chunk is unchanged either
// way - only the new audio_bank field and its consumer (audio_streamer.sv)
// needed to change.
//
// Generated by: py tools/convert_audio.py --dir ALBUM_DIR [--use-tags]
// Supports MAX_TRACKS=512 (Section 41; was 32) - track_idx/lib_idx are 9
// bits, track_count is 10 bits. No FPGA recompile needed to add or change
// tracks within that cap. Every address width here already derives from
// MAX_TRACKS via $clog2 (see Section 33/34 below for why), so this jump
// needed no logic changes in this file - only the port widths (sized off
// the caller's chosen MAX_TRACKS, not hardcoded) and the parameter value
// passed in from core_top.v.
//
// Two read ports:
//   Primary (track_idx):  used by audio path; outputs track_start/track_chunks/
//                         track_title (BE) / track_artist (BE).
//   Secondary (lib_idx):  used by Library tab display; outputs lib_title_le /
//                         lib_artist_le (little-endian for easy variable indexing).
//
// Section 33 MEMORY REDESIGN (fitter failure fix): the original layout stored
// pram[] as a FLAT 32-bit-wide word array (TOTAL_WORDS = MAX_TRACKS*32) and
// read ~25 DIFFERENT word addresses per port every cycle (one direct read per
// title/artist character-group) to reassemble one track's fields. That is not
// a pattern Quartus's memory inference recognizes as block RAM (a block RAM
// port has exactly ONE address per cycle) - it was being built as
// distributed registers + a large per-field multiplexer network instead. That
// scaled with MAX_TRACKS: fine at MAX_TRACKS=8, but at MAX_TRACKS=32 (Section
// 32) it blew the device's LAB budget ("Fitter requires 2256 LABs but the
// device contains only 1848"). Fixed by storing ONE WIDE ROW PER TRACK
// (pram[track_row] is a single 1024-bit vector = the track's whole 128-byte
// record) so each read port does exactly ONE address lookup; the individual
// fields are then extracted by bit-slicing that single wide value, which is
// free wire routing, not additional memory reads. track_count is now an
// incremental counter watching the write stream (any word-0 write with a
// nonzero chunk_count bumps it) instead of a 32-address scan every cycle,
// for the same reason.
//
// Section 33 ROUND 2 (first attempt made the fitter failure WORSE - 142% ALM
// utilization instead of 120%): the write side originally wrote directly into
// a VARIABLE-BIT-OFFSET slice of a pram[] ARRAY ELEMENT
// (`pram[wr_row][wr_word*32 +: 32] <= bridge_wr_data`). That combination -
// indexed array element + a runtime-variable sub-word offset within it - is
// ALSO not a standard block-RAM write template (block RAM write ports expect
// either a full-width write or STATIC, fixed-lane byte/word enables, not an
// address that shifts by a variable amount), so pram[] was very likely still
// being built as raw registers despite the read-side fix, and the read side
// now had to mux a full 1024-bit row instead of the ~800 bits actually used -
// worse, not better. FIXED by staging each track's words 0..30 into a plain
// (non-array) 992-bit register as they stream in - a variable-offset write
// into a lone register is just normal datapath logic, no memory-inference
// ambiguity at all - and committing the ENTIRE 1024-bit row to pram[] in ONE
// single full-width write when the last word (31) arrives. This relies on
// bridge writes landing in strictly ascending word order within each track
// (true for this one-shot sequential file load, same assumption the FSM
// below already makes about the overall load completing once, in order).
//
// Section 34 (fitter STILL failing after round 2, 116% ALM): "Total block
// memory bits" in the Fitter report never moved from 481,536 across every
// attempt (original flat array, round 1, round 2) - the giveaway that pram[]
// was NEVER actually becoming block RAM, regardless of read/write pattern
// cleanliness. Root cause: track_row/lib_row were plain combinational reads
// (`wire = pram[idx]`), and Cyclone V M10K block RAM ONLY has synchronous
// (registered) read ports - a bare combinational array read is unconditionally
// built as registers/muxes, never block RAM, no matter how clean the
// addressing is. FIXED by registering both reads (see track_row/lib_row
// below). This adds 1 cycle of read latency, which is invisible for lib_idx
// (row changes land during blanking) but DOES matter for track_idx, whose
// consumers (title_ram/artist_ram refresh, audio_streamer's chunk_idx seed)
// previously assumed same-cycle availability - handled in core_top.v by
// feeding track_idx a PRE-FETCHED "next index" one cycle before track_sel
// visibly changes (pram_read_idx_next), preserving the exact same external
// timing as before.

`default_nettype none

module playlist_ram #(
    parameter logic [15:0] SLOT_ID     = 16'd17,
    parameter logic [31:0] BRIDGE_BASE = 32'h2100_0000,  // window size = MAX_TRACKS*128 bytes
    parameter int          MAX_TRACKS  = 512              // 512 x 128 bytes = 65536 bytes
) (
    input  logic        clk,
    input  logic        reset,

    // APF dataslot read - one request at boot to load playlist.bin
    output logic        target_dataslot_read,
    output logic [15:0] target_dataslot_id,
    output logic [31:0] target_dataslot_slotoffset,
    output logic [31:0] target_dataslot_bridgeaddr,
    output logic [31:0] target_dataslot_length,
    input  logic        target_dataslot_done,

    // APF bridge writes fill pram after the dataslot read completes
    input  logic        bridge_wr,
    input  logic [31:0] bridge_addr,
    input  logic [31:0] bridge_wr_data,

    output logic        loaded,

    // Primary read port: audio path (track_idx selects row)
    input  logic [8:0]  track_idx,
    output logic [15:0] track_start,      // LOCAL chunk offset within track_audio_bank's data slot
    output logic [15:0] track_chunks,     // chunk count for this track
    output logic [511:0] track_title,     // 64 ASCII bytes big-endian; [511:504]=char 0
    output logic [255:0] track_artist,    // 32 ASCII bytes big-endian; [255:248]=char 0
    output logic [3:0]  track_audio_bank, // which "Audio Bank N" data slot holds this track's audio
    output logic [9:0]  track_count,      // number of entries with non-zero chunk_count

    // Secondary read port: Library tab display (lib_idx selects row, LE output)
    input  logic [8:0]  lib_idx,
    output logic [511:0] lib_title_le,    // 64 chars little-endian; [7:0]=char 0
    output logic [255:0] lib_artist_le    // 32 chars little-endian; [7:0]=char 0
);

    localparam int WORDS_PER_TRACK = 32;
    localparam int RECORD_BITS     = WORDS_PER_TRACK * 32; // 1024 bits/track (128 bytes)
    localparam int STAGE_BITS      = RECORD_BITS - 32;      // 992 bits = words 0..30
    localparam int ROW_AW          = $clog2(MAX_TRACKS);     // 5 bits for 32
    localparam int WSEL_BITS       = $clog2(WORDS_PER_TRACK); // 5 bits (word-within-row)
    localparam int WORD_AW         = ROW_AW + WSEL_BITS;      // 10 bits (flat word index width)

    // ONE WIDE ROW PER TRACK, written as a single full-width commit per track
    // (see the staging register below) - see header notes above for why.
    (* ramstyle = "M10K" *) logic [RECORD_BITS-1:0] pram [0:MAX_TRACKS-1];

    // Single-shot loader FSM (4-state, confirmed working pattern).
    typedef enum logic [1:0] { S_REQ, S_WAIT_CLEAR, S_WAIT_DONE, S_DONE } loader_state_t;
    loader_state_t state;

    // Write-side address decode: flat word index -> (row, word-within-row).
    wire               in_range   = bridge_wr && (bridge_addr[31:(WORD_AW+2)] == BRIDGE_BASE[31:(WORD_AW+2)]);
    wire [WORD_AW-1:0] word_index = bridge_addr[WORD_AW+1:2];
    wire [ROW_AW-1:0]  wr_row     = word_index[WORD_AW-1:WSEL_BITS];
    wire [WSEL_BITS-1:0] wr_word  = word_index[WSEL_BITS-1:0];
    wire               wr_last_word = (wr_word == WSEL_BITS'(WORDS_PER_TRACK-1));

    // Staging register: accumulates one track's words 0..30 as they stream
    // in (a variable-offset write into a lone register is ordinary datapath
    // logic, not a memory-array access, so there's no inference ambiguity
    // here). NOT gated by reset, same reasoning as pram[] below.
    logic [STAGE_BITS-1:0] stage_reg;

    // pram capture: NOT gated by reset so APF static boot load populates pram[]
    // before Reset Exit fires. (See CLAUDE.md APF static boot load behavior note.)
    // Every word up to the last one just updates the staging register; the
    // last word (31) combines with the already-staged words 0..30 into ONE
    // single full-width write to pram[wr_row] - the simplest, most reliably
    // block-RAM-inferable write pattern there is.
    always_ff @(posedge clk) begin
        if (in_range) begin
            if (wr_last_word)
                pram[wr_row] <= {bridge_wr_data, stage_reg};
            else
                stage_reg[wr_word*32 +: 32] <= bridge_wr_data;
        end
    end

    // track_count: incremented as word-0 (header) writes stream in, instead of
    // scanning all MAX_TRACKS rows combinationally every cycle (same class of
    // "many simultaneous addresses" cost as the old title/artist reads would
    // have reintroduced for this one field). Exactly one word-0 write occurs
    // per track during the one-shot boot load, so this can't double-count.
    //
    // NOT gated by reset - same reasoning as pram[]/stage_reg above, and the
    // exact bug this project's CLAUDE.md already documents (APF static boot
    // load behavior): the Playlist slot's real bridge_wr writes all land
    // BEFORE Reset Exit, i.e. while `reset` is still asserted. An async-reset
    // register here would re-force track_count to 0 on every clk edge for the
    // whole duration of that load (its `if (reset)` branch re-triggers on
    // every posedge clk while reset stays high, same priority as the actual
    // increment), permanently losing every real increment - by the time reset
    // deasserts (Reset Exit), the one-shot load has already finished and never
    // repeats (no re-DMA), so track_count would be stuck at 0 forever. This
    // was confirmed the actual root cause of the Library tab showing a
    // totally blank list (row_has_track = list_track_idx < track_count is
    // false for every row when track_count reads 0) - see POCKETPLAYER_NOTES.txt.
    always_ff @(posedge clk) begin
        if (in_range && (wr_word == '0) && (bridge_wr_data[15:0] != 16'd0))
            track_count <= track_count + 10'd1;
    end

    // FSM: single-shot 4-state loader.
    always_ff @(posedge clk or posedge reset) begin
        if (reset) begin
            state                      <= S_REQ;
            target_dataslot_read       <= 1'b0;
            target_dataslot_id         <= SLOT_ID;
            target_dataslot_slotoffset <= 32'h0;
            target_dataslot_bridgeaddr <= BRIDGE_BASE;
            target_dataslot_length     <= 32'(MAX_TRACKS * 128); // 1024 bytes
            loaded                     <= 1'b0;
        end else begin
            target_dataslot_read <= 1'b0; // default deasserted

            case (state)
                S_REQ: begin
                    target_dataslot_read <= 1'b1;
                    state                <= S_WAIT_CLEAR;
                end
                S_WAIT_CLEAR: begin
                    if (!target_dataslot_done)
                        state <= S_WAIT_DONE;
                end
                S_WAIT_DONE: begin
                    if (target_dataslot_done) begin
                        loaded <= 1'b1;
                        state  <= S_DONE;
                    end
                end
                S_DONE: ;
                default: state <= S_REQ;
            endcase
        end
    end

    // Primary read: ONE address (track_idx) per port. The whole 1024-bit row
    // is a single block-RAM read; the field extraction below is pure
    // bit-slicing of that already-fetched wire (free), not further memory
    // reads - word N of the row is always at bits [N*32 +: 32], matching the
    // write-side's wr_word*32 convention exactly.
    //
    // Section 34: REGISTERED read (was a bare combinational `wire = pram[idx]`).
    // Even after Section 33's read/write pattern fixes, "Total block memory
    // bits" in the Fitter report stayed bit-for-bit IDENTICAL across every
    // attempt - the real remaining reason: Cyclone V M10K block RAM only has
    // SYNCHRONOUS (registered) read ports. A combinational array read is a
    // hard signal to Quartus's memory inference that this can't be block RAM
    // at all, no matter how clean the address/write pattern is - so pram[]
    // was still being built entirely out of registers + muxes in every prior
    // attempt. Fixed by registering the read; core_top.v now feeds track_idx
    // the PREDICTED next-cycle index one cycle before track_sel visibly
    // changes (pram_read_idx_next), so track_title/track_artist/track_start/
    // track_chunks become valid at exactly the same relative cycle external
    // consumers already expected - no timing change outside this module.
    logic [RECORD_BITS-1:0] track_row;
    always_ff @(posedge clk) track_row <= pram[track_idx];
    wire [31:0] track_header_word = track_row[0*32 +: 32];
    // Word 25, byte 100 (top byte of that word, same big-endian convention
    // as every other field here) - see header comment for the on-disk format.
    wire [7:0]  track_audio_bank_byte = track_row[25*32+24 +: 8];
    always_comb begin
        track_start      = track_header_word[31:16];
        track_chunks     = track_header_word[15:0];
        track_audio_bank = track_audio_bank_byte[3:0];
        // Title: 16 words (words 1..16), big-endian
        track_title[511:480] = track_row[1*32  +: 32];
        track_title[479:448] = track_row[2*32  +: 32];
        track_title[447:416] = track_row[3*32  +: 32];
        track_title[415:384] = track_row[4*32  +: 32];
        track_title[383:352] = track_row[5*32  +: 32];
        track_title[351:320] = track_row[6*32  +: 32];
        track_title[319:288] = track_row[7*32  +: 32];
        track_title[287:256] = track_row[8*32  +: 32];
        track_title[255:224] = track_row[9*32  +: 32];
        track_title[223:192] = track_row[10*32 +: 32];
        track_title[191:160] = track_row[11*32 +: 32];
        track_title[159:128] = track_row[12*32 +: 32];
        track_title[127:96]  = track_row[13*32 +: 32];
        track_title[95:64]   = track_row[14*32 +: 32];
        track_title[63:32]   = track_row[15*32 +: 32];
        track_title[31:0]    = track_row[16*32 +: 32];
        // Artist: 8 words (words 17..24), big-endian
        track_artist[255:224] = track_row[17*32 +: 32];
        track_artist[223:192] = track_row[18*32 +: 32];
        track_artist[191:160] = track_row[19*32 +: 32];
        track_artist[159:128] = track_row[20*32 +: 32];
        track_artist[127:96]  = track_row[21*32 +: 32];
        track_artist[95:64]   = track_row[22*32 +: 32];
        track_artist[63:32]   = track_row[23*32 +: 32];
        track_artist[31:0]    = track_row[24*32 +: 32];
    end

    // Secondary read: ONE address (lib_idx) per port, same one-row-then-slice
    // technique. Outputs are little-endian so the display can use
    // lib_title_le[char_idx*8 +: 8].
    // Registered read (see track_row above, Section 34). lib_idx only
    // changes at Library-list row boundaries, which always land during
    // horizontal blanking (hundreds of cycles of margin) - so this module's
    // 1-cycle read latency settles long before the next row's first visible
    // pixel. No external retiming needed for this port.
    logic [RECORD_BITS-1:0] lib_row;
    always_ff @(posedge clk) lib_row <= pram[lib_idx];
    logic [31:0] lib_word; // scratch: holds one word of lib_row per loop iteration below
    always_comb begin
        // Title (64 chars) LE: char n at lib_title_le[n*8 +: 8]
        for (int i = 0; i < 16; i++) begin
            // word i+1 contains chars 4i..4i+3 (big-endian in word)
            lib_word = lib_row[(i+1)*32 +: 32];
            lib_title_le[(i*4+0)*8 +: 8] = lib_word[31:24];
            lib_title_le[(i*4+1)*8 +: 8] = lib_word[23:16];
            lib_title_le[(i*4+2)*8 +: 8] = lib_word[15:8];
            lib_title_le[(i*4+3)*8 +: 8] = lib_word[7:0];
        end
        // Artist (32 chars) LE: char n at lib_artist_le[n*8 +: 8]
        for (int i = 0; i < 8; i++) begin
            lib_word = lib_row[(i+17)*32 +: 32];
            lib_artist_le[(i*4+0)*8 +: 8] = lib_word[31:24];
            lib_artist_le[(i*4+1)*8 +: 8] = lib_word[23:16];
            lib_artist_le[(i*4+2)*8 +: 8] = lib_word[15:8];
            lib_artist_le[(i*4+3)*8 +: 8] = lib_word[7:0];
        end
    end

endmodule
